const Quotes = () => new Promise((resolve, reject) => {
  let arr = [
    'Bagi dunia, kamu mungkin satu orang, tetapi bagi satu orang kamu adalah dunia.',
    'Cinta mungkin hadir karena takdir tapi tak ada salahnya kita saling memperjuangkan.',
    'Cinta adalah d imana kamu selalu punya alasan untuk kembali meski kamu sudah berjalan begitu jauh.',
    'Dalam cinta, menyerah tak selalu berarti kamu lemah. Kadang itu hanya berarti kamu cukup kuat tuk melepaskannya.',
    'Kamu mungkin memegang tanganku untuk sementara waktu, tetapi kamu memegang hatiku selamanya.',
    'Saat aku bersamamu, aku akan melepaskan segala ketakutan dan kecemasan.',
    'Kamu nyaman? Kamu sayang? Tapi cuma dianggap temen? Kadang gitu. Nyamanmu belum tentu nyamannya. Cukup dipahami aja.',
    'Dibilang sayang? Iya. Dibilang cinta? Iya. Dibilang pacar? Bukan.',
    'Apakah namamu WiFi? Soalnya aku bisa merasakan konektivitas.',
    'Bersamamu aku tidak pernah takut lagi menjadi pemimpi.',
    'Move on itu pilihan. Gagal move on itu cobaan. Pura-pura move on itu pencitraan.',
    'Sepurane aku nggak nguber awakmu maneh. Kepastianmu abstrak, podo karo raimu.',
    'You`re just my cup of tea.',
    'My love belongs to you.',
    'I love you - those three words have my life in them.',
    'You are my strength but loving you is my biggest weakness.',
    'I promise that i`ll love you in every step of mine',
    'Aku tidak pernah keberatan menunggu siapa pun berapa lama pun selama aku mencintainya.',
    'Aku tak ingin berakhir seperti mereka, saling mencintai. Lantas kehilangan dan kini mereka hanya mengenang dan merenung dari jauh.',
    'Kau mencintaiku tanpa sepatah kata, aku mencintaimu, dengan satu kata yang tak pernah patah.',
    'Allah menciptakan senja untuk mengingatkanku untuk pulang pada cinta yang kukenang.',
    'Cinta tak berupa tatapan satu sama lain, tetapi memandang keluar bersama ke arah yang sama.',
    'Cinta tidak terlihat dengan mata, tetapi dengan hati.',
    'Cinta itu layaknya angin, aku tidak bisa melihatnya tetapi aku bisa merasakannya.',
    'Cinta tidak pernah menuntut, cinta selalu memberi. Cinta selalu menderita, tanpa pernah meratap, tanpa pernah mendendam.',
    'Masa lalu saya adalah milik saya, masa lalu kamu adalah milik kamu, tapi masa depan adalah milik kita.',
    'Bahagia itu kita yang ciptain, bukan mereka.',
    'Cinta itu, rela melihat orang yang kita cintai bahagia bareng orang lain.',
    'Aku hanyalah kunang-kunang, dan kau hanyalah senja, dalam gelap kita berbagi, dalam gelap kita abadi.',
    'Dalam diam, aku memperjuangkan cintamu dalam doaku.',
    'Terkadang wanita ingin mengungkapkan semua yg ada di dalam hatinya, namun ia lebih menahan diri untuk tidak mengucapkannya demi kebaikan.',
    'I miss my old friends. I mean, the crazy, stupid, fool, weird, awkward, mad, solid, cool, smart, kindly, faithfully and honestly.',
    'Jangan slalu berpikir "kapan kita akan selalu bersama" & "kapan kita akan berpisah" jalani saja dengan sebaik-baiknya. Waktu yang menjawab.',
    'Ga perlu nyalahin diri sendiri ketika orang yg lo sayang direbut orang. Karena bisa jadi, doi yg ga bisa jaga hati atau bahkan MURAHAN :)',
    'Yg namanya sahabat itu wajar kok kalo pernah bertengkar. Tapi inget, nggak ada pertengkaran yg lebih penting dari sebuah persahabatan. :)',
    'Sahabat itu "Lo kenapa? Sini dong cerita". Temen musiman itu "Yelah cengeng lo, Galau mulu".',
    'Nurut aja sama pacar, selagi dia masih suka larang-larang kamu. Kalo dia udah ga pernah larang-larang berarti dia udah ga sayang kamu~',
    'Jalanin hubungan yang serius itu harus sama orang yang serius sama kita, jangan yang ga serius sama kita. Percuma !',
    'Mantan itu masa lalu, kalo pikirannya ke masa lalu mulu, lo ga bakal punya masa depan.',
    'Misalnya ada suatu kondisi dmn aku bnran lg galauin km. Trus km ngetweet galau seolah2 itu buat aku padahal buat org lain. Itu babi namanya.',
    'Padahal berubah untuk menjadi lebih baik lagi itu ga ada salahnya, memang butuh waktu kok. Dan cara penyampaian nasehatnya harus halus :)',
    'Kadang air mata adalah tanda lega, bukan tanda kalau dia lemah.',
    'Ga selamanya sabar itu enak. Terkadang, kamu harus merasakan sakitnya. Perihnya dari sabar itu sendiri.',
    'Yang ngaku temen sih banyak, tapi nggak tau berapa yang beneran.',
    'Sedih itu gak papa, tapi jangan lama-lama ya. Karena setelah kesedihan itu kamu harus dapatkan kebahagiaan lagi. :)',
    'Jujur aku kangen banget sama kamu. Yang dulu :)',
    'Mulai sekarang bersikap biasa aja deh.. Gak terlalu ngarep-ngarep amat.',
    'Pacar yang baik adalah pacar yang ikut turut menjaga image pasangannya sendiri.',
    'Selalu ada saatnya sabarmu membuahkan hasil. Mungkin memang tidak sekarang, tapi waktu punya alasan tersendiri kenapa kamu harus sabar.',
    'Pacar yang baik adalah pacar yang ikut turut menjaga image pasangannya sendiri.',
    'Cowo yang sayang dan perhatian sama ibunya pasti kalo punya pacar, dia juga memperlakukan pacarnya seperti itu. Catet !',
    'Nih bro yang harus lo tau dari cewe. 1. Cewe itu ga pernah salah. 2. Kalo cewe salah, balik ke nomor 1 dan lo yang harus minta maap bro..',
    '"Yaudah iya" artinya "Aku cape, kamu susah dibilangin"',
    'Jika kamu selalu ingin mencari yang terbaik, ingatlah bahwa banyak seseorang yang jauh lebih baik dari kamu, namun dia tetap memilih kamu~',
    'Pengen sukses dulu, Pengen bahagiain orang tua dulu. Mumpung mereka masih ada! Masalah pacar mah belakangan. Yg penting sukses dulu skrg.',
    'Jika hubungan itu seperti pohon. Rawatlah pohon itu dri kecil hingga besar. Dari akarnya dulu, baru daunnya, lalu akan memetik buah yg manis',
    'Cewek yang lagi broken itu rentan ditikung. Jangan membuat wanitamu menangis sebelum ada pria lain yang menghapus air matanya.',
    '"Have fun ya" artinya "Aku ga rela kamu seneng-seneng sama orang, bukan sama aku :("',
    'Selama lo nggak ngerugiin diri sendiri dan juga siapa pun, tetaplah berbahagia dan bodo amat dengan omongan orang lain.',
    'Bisanya emang kalo udah sayang, apa-apanya dibelain banget.',
    'Cemburu sih engga, cuma aku ga suka aja kalo ada orang lain yang bikin kamu ketawa selain aku~',
    'Kalo ga saling sayang, gak bakal ada yg namanya pertengkaran dlm suatu hubungan. Pertengkaran trjadi krn kekecewaan terhadap sebuah harapan~',
    'Gak semua cewe itu suka dilarang-larang. Sebagai pria kita harus bisa mengerti dan memahami karakteristik wanita yang akan kita hadapi.',
    'Kalo pacar kamu macem-macem, kamu jangan bales macem-macem balik. Kalo kamu bales macem-macem berarti kamu sama aja murahannya kaya dia.',
    'Cewek itu gak bakalan mau ngeluarin "airmata", kalo dia gak "sayang".',
    'Selalu ada saatnya sabarmu membuahkan hasil. Mungkin memang tidak sekarang, tapi waktu punya alasan tersendiri kenapa kamu harus sabar.',
    'Tired of fake people, fake smiles, fake hugs, fake friend, false hopes.',
    'Perlakukanlah pasanganmu seperti Raja / Ratu sebelum ada orang lain yang memperlakukan pasanganmu seperti Raja / Ratu nya.',
    'Ketika kamu sedang lupa dengannya karena kamu sedang dekat dengan orang lain, ingatlah dia yang selalu menjaga hatinya hanya untuk kamu.',
    'Karena berjuang musti liat-liat apa yang di perjuangin. Kalo yang di perjuangin sudah bahagia dengan yang lain, lebih baik tinggalin. :)',
    'Kalau dia sayang, dia pasti peduli, mendatangi kamu. Kalau dia nggak melakukan itu, cari yang lebih mau perjuangin kamu. :)',
    'Jangan memaksa untuk angkat bicara disaat kita berada dalam sebuah emosi sesaat. Tenangkan diri kita masing-masing dulu.',
    'Cerita, curhat sepuas-puasnya. Nangis sejadi-jadinya, habis itu lega. Kadang hidup perlu begituan.',
    'Kepada, Lelaki. Jadilah sebaik-baiknya kamu. Perempuan yang memilihmu, menaruh harap ingin baik pula masa depannya. Kerja keraslah.',
    'Curhatin pacar sama temen, terus temen ngasih masukan yg bisa buat kamu nyaman, setelah kamu nyaman sama temen, terus jadi demen. Klasik~',
    'Cerita, curhat sepuas-puasnya. Nangis sejadi-jadinya, habis itu lega. Kadang hidup perlu begituan.',
    'Sabar tanpa batas. Memaafkan tanpa menghitung. Ikhlas tanpa mengharap imbalan. :")',
    'Dia kece, yg ngedeketin pasti banyak, yg mau jadi pacarnya pasti banyak, aku mungkin menang gak ya? | Usaha dulu, gak ada yg gak mungkin. :)',
    'Pertahanin orang yang mau pertahanin kamu juga. Jangan pertahanin orang yang ga pertahanin kamu. Sia-sia loh~',
    'Kamu nggak capek bikin orang berharap, kangen, dan berjuang sendirian? Nggak nyesel bikin orang nangisin kamu?',
    'Wajar cemburu, karna sayang. Wajar nunggu kabar, karna khawatir. Lebay? Iya. Coba sini tuker posisi, biar ngerasain sakitnya dibilang lebay.',
    'Kalo kamu sayang aku, aku bisa lebih sayang sama kamu. Kalo kamu macem-macem sama aku, aku bisa lebih macem-macem.',
    'Pria sejati itu pria yang bisa membuat wanita2 lain cemburu dan iri sama wanitanya. Bukan membuat wanitanya cemburu sama wanita2 lain. ;)',
    'Orang yg bener-bener sayang itu dia nggak bakal macem-macem di belakang kita. Meskipun jauh, dia pasti bakal jaga kepercayaan kita. :)',
    'Seseorang yang bisa membuat aku sering merasa khawatir, berarti dialah orang yang sangat aku sayang.',
    'Ada saatnya dimana sangat merindukan seseorang hingga ingin menjemputnya dari mimpi dan memeluknya di dunia nyata.',
    'Nilai plus dari seorang cewe itu ya dari attitudenya. Walaupun cantik tapi ga punya attitude, itu minus.',
    'Semua orang tahu bagaimana mencintai, tapi hanya sebagian orang yang tahu bagaimana tetap tinggal di satu hati untuk jangka waktu yang lama.',
    'Aku emg egois! aku pgn km cuma syg sm aku. aku pgn km dktnya sm aku doang. aku pgn cuma aku aja yg bs bkn kamu seneng. egois bgt ya. hehe:")',
    'Kunci langgeng dalam hubungan itu cuma gak malu / gengsi untuk minta maaf duluan kalo emang ngerasa salah. Itu aja dulu~',
    'Orang yang kamu sayang, belum tentu selalu ada untuk kamu. Orang yang sayang sama kamu, udah pasti dia selalu ada untuk kamu.',
    'Orang yang kamu sayang, belum tentu selalu ada untuk kamu. Orang yang sayang sama kamu, udah pasti dia selalu ada untuk kamu.',
    'Maaf banget kalo aku ga bisa kaya mantan kamu, aku ya aku, dia ya dia. Aku ga bisa kaya dia, karena aku jauh lebih baik daripada dia~',
    'Hargai dan mengertilah dia selama dia masih berada di sisimu. Penyesalan selalu datang setelah suatu kesalahan terlanjur diperbuat.',
    'di saat kamu benar-benar merasa takut kehilangan, disitulah, kamu benar-benar ada pada titik sayang paling tulus.',
    'Suatu hari, orang yang ngomong "jangan lupa sholat ya" akan kalah sama orang yang ngomong "sholat bareng aku yuk, aku imamnya" :)',
    'Senyum memiliki 2 arti, yang pertama kita benar-benar bahagia, yang kedua kita berusaha menyembunyikan sebuah kesedihan. :)',
    'Menyenangkan adalah ketika kita dijadikan prioritas di antara sekian kegiatannya. Bukan yang utama, namun yang selalu diingat adanya.',
  ]
  let acak = arr[Math.floor(Math.random() * arr.length)]
  resolve(acak)
})

module.exports = Quotes
